// <auto-generated />
namespace ITISystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Attendance_std : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Attendance_std));
        
        string IMigrationMetadata.Id
        {
            get { return "201703260822537_Attendance_std"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
