// <auto-generated />
namespace ITISystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Std_Crs_Instr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Std_Crs_Instr));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251608486_Std_Crs_Instr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
