// <auto-generated />
namespace ITISystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManageStudentandcrs_gradeForStudentandDisplayEvaluationOfInstructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManageStudentandcrs_gradeForStudentandDisplayEvaluationOfInstructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201704011837363_ManageStudentandcrs_gradeForStudentandDisplayEvaluationOfInstructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
