// <auto-generated />
namespace ITISystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mange_std_dprt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mange_std_dprt));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281620574_mange_std_dprt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
